### ISSUE TITLE
react-select-checked placeholder disappears with some options checked and no input string matches

### ISSUE THREAD

**Issue by kalletlak** [thehyve/react-select-checked#21]

**Comment by fedde-s** [comment]
Did you reproduce this on [v0.1.9](https://github.com/thehyve/react-select-checked/releases/tag/v0.1.9) or newer of the component? The description sounds similar to the one I fixed in pull request https://github.com/thehyve/react-select-checked/pull/19.

**Comment by fedde-s** [comment]
But apparently there was a follow-up in https://github.com/cBioPortal/cbioportal/issues/4476#issuecomment-409106776, in which the way it was used in cBioPortal somehow broke things again.

**Comment by zhx828** [comment]
@fedde-s @rnugraha the issue still exists in the v0.1.10. You can see from the beta study view. http://www.cbioportal.org/beta/newstudy?id=acc_tcga

**Comment by fedde-s** [comment]
@zhx828, do you have any ideas on how to fix it? If so, feel free to make a pull request!
